info:
  title: APIdesignDEMO
  version: 1.0.0
  description: provides bank atm  api functions
paths:
  '/deposit/{pin}':
    post:
      tags:
        - Deposit
      summary: Returns customer withdrawal information
      operationId: PUT_deposit-pin
      parameters:
        - name: pin
          in: path
          description: The pin of customers account
          required: true
          type: integer
          minimum: 1
      responses:
        '200':
          description: A deposit object
          schema:
            type: object
            properties:
              account_number:
                type: number
                example: 1.12233445566E11
              account_name:
                type: string
                example: Vinula Uthsara
              deposit_amount:
                type: string
                example: 'Rs. 20,000.00'
        '400':
          description: The specified pin is invalid
        '404':
          description: An account with the specified pin was not found
  '/withdrawal/{pin}':
    post:
      tags:
        - Withdrawal
      summary: Returns customer withdrawal information
      operationId: PUT_withdrawal-pin
      parameters:
        - name: pin
          in: path
          description: The pin of customers account
          required: true
          type: integer
          minimum: 1
      responses:
        '200':
          description: A withdrawal object
          schema:
            type: object
            properties:
              account_number:
                type: number
                example: 1.12233445566E11
              account_name:
                type: string
                example: Vinula Uthsara
              withdrawal_amount:
                type: string
                example: 'Rs. 20,000.00'
        '400':
          description: The specified pin is invalid
        '404':
          description: An account with the specified pin was not found
  '/accountinfo/{pin}':
    get:
      tags:
        - Accountinfo
      summary: Returns customer account information
      operationId: GET_accountinfo-pin
      parameters:
        - name: pin
          in: path
          description: The pin of customers account
          required: true
          type: integer
          minimum: 1
      responses:
        '200':
          description: A customer account object
          schema:
            type: object
            properties:
              account_number:
                type: number
              account_name:
                type: string
              account_balance:
                type: string
        '400':
          description: The specified pin is invalid
        '404':
          description: An account with the specified pin was not found
definitions:
  inline_response_200_1:
    properties:
      account_number:
        type: number
        example: 1.12233445566E11
      account_name:
        type: string
        example: Vinula Uthsara
      withdrawal_amount:
        type: string
        example: 'Rs. 20,000.00'
  inline_response_200:
    properties:
      account_number:
        type: number
        example: 1.12233445566E11
      account_name:
        type: string
        example: Vinula Uthsara
      account_balance:
        type: string
        example: 'Rs. 500,000.00'
  inline_response_200_2:
    properties:
      account_number:
        type: number
        example: 1.12233445566E11
      account_name:
        type: string
        example: Vinula Uthsara
      deposit_amount:
        type: string
        example: 'Rs. 20,000.00'
schemes:
  - https
basePath: /Vinula/APIdesignLab/1.0.0
host: virtserver.swaggerhub.com
swagger: '2.0'
